use std::{fmt::Write as _, fs, path::Path};

use anyhow::{Context, Result};

use super::{
    load::load_registry_from_file,
    model::LanguageRegistry,
    validate::{
        collect_exact_name_index, collect_extension_index, style_const_name,
        validate_style_identifier_collisions,
    },
};

/// # Errors
///
/// Returns an error when the output cannot be written.
pub fn generate_language_data_file(input: &Path, output: &Path) -> Result<()> {
    let registry = load_registry_from_file(input)?;
    let generated = render_language_module(&registry)?;

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!("failed to create output directory `{}`", parent.display())
        })?;
    }

    fs::write(output, generated)
        .with_context(|| format!("failed to write `{}`", output.display()))
}

/// # Errors
///
/// Returns an error when rendering fails due to invalid identifiers.
pub fn render_language_module(registry: &LanguageRegistry) -> Result<String> {
    validate_style_identifier_collisions(registry)?;

    let exact_index = collect_exact_name_index(registry)?;
    let extension_index = collect_extension_index(registry)?;
    let mut output = String::new();

    render_prelude(&mut output)?;
    render_comment_styles(&mut output, registry)?;
    render_builtin_languages(&mut output, registry)?;
    render_lookup_indices(&mut output, &exact_index, &extension_index)?;
    render_lookup_functions(&mut output)?;

    Ok(output)
}

fn render_prelude(output: &mut String) -> Result<()> {
    writeln!(
        output,
        "// This file is generated by `sephera_tools generate-language-data`."
    )?;
    writeln!(
        output,
        "// Do not edit by hand; update `config/languages.yml` instead."
    )?;
    writeln!(output)?;
    writeln!(output, "use std::path::Path;")?;
    writeln!(output)?;
    writeln!(output, "use phf::{{Map, phf_map}};")?;
    writeln!(output)?;
    writeln!(
        output,
        "use crate::core::config::{{CommentStyle, LanguageConfig}};"
    )?;
    writeln!(output)?;
    writeln!(
        output,
        "pub type LanguageMatch = (usize, &'static LanguageConfig);"
    )?;
    writeln!(output)?;
    Ok(())
}

fn render_comment_styles(
    output: &mut String,
    registry: &LanguageRegistry,
) -> Result<()> {
    for style_key in registry.comment_styles.keys() {
        let style = &registry.comment_styles[style_key];
        let const_name = style_const_name(style_key)?;
        writeln!(output, "#[rustfmt::skip]")?;
        writeln!(
            output,
            "pub const {const_name}: CommentStyle = CommentStyle::new({}, {}, {});",
            render_option(style.single_line.as_deref()),
            render_option(style.multi_line_start.as_deref()),
            render_option(style.multi_line_end.as_deref())
        )?;
    }
    writeln!(output)?;
    Ok(())
}

fn render_builtin_languages(
    output: &mut String,
    registry: &LanguageRegistry,
) -> Result<()> {
    writeln!(output, "#[rustfmt::skip]")?;
    writeln!(
        output,
        "pub static BUILTIN_LANGUAGES: &[LanguageConfig] = &["
    )?;
    for language in &registry.languages {
        let style_name = style_const_name(&language.comment_style_key)?;
        writeln!(
            output,
            "    LanguageConfig::new({}, &[{}], &[{}], &{style_name}),",
            rust_string_literal(&language.name),
            join_string_literals(&language.extensions),
            join_string_literals(&language.exact_names)
        )?;
    }
    writeln!(output, "];")?;
    writeln!(output)?;
    writeln!(output, "#[rustfmt::skip]")?;
    writeln!(output, "#[must_use]")?;
    writeln!(
        output,
        "pub const fn builtin_languages() -> &'static [LanguageConfig] {{"
    )?;
    writeln!(output, "    BUILTIN_LANGUAGES")?;
    writeln!(output, "}}")?;
    writeln!(output)?;
    Ok(())
}

fn render_lookup_indices(
    output: &mut String,
    exact_index: &[(&str, usize)],
    extension_index: &[(&str, usize)],
) -> Result<()> {
    render_index(output, "EXACT_NAME_INDEX", exact_index)?;
    writeln!(output)?;
    render_index(output, "EXTENSION_INDEX", extension_index)?;
    writeln!(output)?;
    Ok(())
}

fn render_index(
    output: &mut String,
    name: &str,
    entries: &[(&str, usize)],
) -> Result<()> {
    writeln!(output, "#[rustfmt::skip]")?;
    writeln!(
        output,
        "static {name}: Map<&'static str, usize> = phf_map! {{"
    )?;
    for (key, index) in entries {
        writeln!(output, "    {} => {index}usize,", rust_string_literal(key))?;
    }
    writeln!(output, "}};")?;
    Ok(())
}

fn render_lookup_functions(output: &mut String) -> Result<()> {
    writeln!(output, "#[rustfmt::skip]")?;
    writeln!(output, "#[must_use]")?;
    writeln!(
        output,
        "pub fn language_for_path(path: &Path) -> Option<LanguageMatch> {{"
    )?;
    writeln!(output, "    let file_name = path.file_name()?.to_str()?;")?;
    writeln!(output)?;
    writeln!(
        output,
        "    if let Some(&index) = EXACT_NAME_INDEX.get(file_name) {{"
    )?;
    writeln!(output, "        return Some(language_match(index));")?;
    writeln!(output, "    }}")?;
    writeln!(output)?;
    writeln!(output, "    let extension = path.extension()?.to_str()?;")?;
    writeln!(
        output,
        "    EXTENSION_INDEX.get(extension).map(|&index| language_match(index))"
    )?;
    writeln!(output, "}}")?;
    writeln!(output)?;
    writeln!(output, "#[rustfmt::skip]")?;
    writeln!(output, "#[must_use]")?;
    writeln!(
        output,
        "fn language_match(index: usize) -> LanguageMatch {{"
    )?;
    writeln!(output, "    (index, &BUILTIN_LANGUAGES[index])")?;
    writeln!(output, "}}")?;
    Ok(())
}

fn join_string_literals(values: &[String]) -> String {
    values
        .iter()
        .map(String::as_str)
        .map(rust_string_literal)
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_option(value: Option<&str>) -> String {
    value.map_or_else(
        || "None".to_owned(),
        |value| format!("Some({})", rust_string_literal(value)),
    )
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}
