// This file is generated by `sephera_tools generate-language-data`.
// Do not edit by hand; update `config/languages.yml` instead.

use std::path::Path;

use phf::{Map, phf_map};

use crate::core::config::{CommentStyle, LanguageConfig};

pub type LanguageMatch = (usize, &'static LanguageConfig);

#[rustfmt::skip]
pub const ADA_STYLE: CommentStyle = CommentStyle::new(Some("--"), Some("/*"), Some("*/"));
#[rustfmt::skip]
pub const ASM_STYLE: CommentStyle = CommentStyle::new(Some(";"), None, None);
#[rustfmt::skip]
pub const AUTOHOTKEY_STYLE: CommentStyle = CommentStyle::new(Some(";"), Some("/*"), Some("*/"));
#[rustfmt::skip]
pub const BASIC_STYLE: CommentStyle = CommentStyle::new(Some("'"), None, None);
#[rustfmt::skip]
pub const BATCHFILE_STYLE: CommentStyle = CommentStyle::new(Some("REM"), None, None);
#[rustfmt::skip]
pub const C_STYLE: CommentStyle = CommentStyle::new(Some("//"), Some("/*"), Some("*/"));
#[rustfmt::skip]
pub const CLOJURE_STYLE: CommentStyle = CommentStyle::new(Some(";"), None, None);
#[rustfmt::skip]
pub const COBOL_STYLE: CommentStyle = CommentStyle::new(Some("*>"), None, None);
#[rustfmt::skip]
pub const COFFEE_SCRIPT_STYLE: CommentStyle = CommentStyle::new(Some("###"), Some("/*"), Some("*/"));
#[rustfmt::skip]
pub const EIFFEL_STYLE: CommentStyle = CommentStyle::new(Some("--"), None, None);
#[rustfmt::skip]
pub const ELIXIR_STYLE: CommentStyle = CommentStyle::new(Some("#"), Some("\"\"\""), Some("\"\"\""));
#[rustfmt::skip]
pub const ERLANG_STYLE: CommentStyle = CommentStyle::new(Some("%%"), None, None);
#[rustfmt::skip]
pub const FORTRAN_STYLE: CommentStyle = CommentStyle::new(Some("!"), None, None);
#[rustfmt::skip]
pub const FSHARP_STYLE: CommentStyle = CommentStyle::new(Some("//"), Some("(*"), Some("*)"));
#[rustfmt::skip]
pub const GODOT_STYLE: CommentStyle = CommentStyle::new(Some("#"), None, None);
#[rustfmt::skip]
pub const HASKELL_STYLE: CommentStyle = CommentStyle::new(Some("--"), Some("{-"), Some("-}"));
#[rustfmt::skip]
pub const HTML_STYLE: CommentStyle = CommentStyle::new(None, Some("<!--"), Some("-->"));
#[rustfmt::skip]
pub const JULIA_STYLE: CommentStyle = CommentStyle::new(Some("#"), Some("#="), Some("=#"));
#[rustfmt::skip]
pub const LISP_STYLE: CommentStyle = CommentStyle::new(Some(";"), Some("#|"), Some("|#"));
#[rustfmt::skip]
pub const LUA_STYLE: CommentStyle = CommentStyle::new(Some("--"), Some("--[["), Some("]]"));
#[rustfmt::skip]
pub const MATLAB_STYLE: CommentStyle = CommentStyle::new(Some("%"), Some("%{"), Some("}%"));
#[rustfmt::skip]
pub const MESON_STYLE: CommentStyle = CommentStyle::new(Some("#"), Some("/*"), Some("*/"));
#[rustfmt::skip]
pub const NIM_STYLE: CommentStyle = CommentStyle::new(Some("#"), Some("#["), Some("]#"));
#[rustfmt::skip]
pub const NO_COMMENT: CommentStyle = CommentStyle::new(None, None, None);
#[rustfmt::skip]
pub const OCAML_STYLE: CommentStyle = CommentStyle::new(None, Some("(*"), Some("*)"));
#[rustfmt::skip]
pub const PASCAL_STYLE: CommentStyle = CommentStyle::new(Some("//"), Some("{"), Some("}"));
#[rustfmt::skip]
pub const PERL_STYLE: CommentStyle = CommentStyle::new(Some("#"), Some("="), Some("=cut"));
#[rustfmt::skip]
pub const PYTHON_STYLE: CommentStyle = CommentStyle::new(Some("#"), Some("\"\"\""), Some("\"\"\""));
#[rustfmt::skip]
pub const RUBY_STYLE: CommentStyle = CommentStyle::new(Some("#"), Some("=begin"), Some("=end"));
#[rustfmt::skip]
pub const SHELL_STYLE: CommentStyle = CommentStyle::new(Some("#"), None, None);
#[rustfmt::skip]
pub const SMALLTALK_STYLE: CommentStyle = CommentStyle::new(Some("\""), None, None);
#[rustfmt::skip]
pub const SQL_STYLE: CommentStyle = CommentStyle::new(Some("--"), Some("/*"), Some("*/"));
#[rustfmt::skip]
pub const TEX_STYLE: CommentStyle = CommentStyle::new(Some("%"), None, None);
#[rustfmt::skip]
pub const VHDL_STYLE: CommentStyle = CommentStyle::new(Some("--"), None, None);
#[rustfmt::skip]
pub const VIM_STYLE: CommentStyle = CommentStyle::new(Some("\""), None, None);

#[rustfmt::skip]
pub static BUILTIN_LANGUAGES: &[LanguageConfig] = &[
    LanguageConfig::new("Python", &[".py"], &[], &PYTHON_STYLE),
    LanguageConfig::new("Java", &[".java"], &[], &C_STYLE),
    LanguageConfig::new("JavaScript", &[".js", ".mjs"], &[], &C_STYLE),
    LanguageConfig::new("Shell Script", &[".sh"], &[], &SHELL_STYLE),
    LanguageConfig::new("C++", &[".c++", ".cc", ".cpp", ".cxx"], &[], &C_STYLE),
    LanguageConfig::new("C", &[".c"], &[], &C_STYLE),
    LanguageConfig::new("Golang", &[".go"], &[], &C_STYLE),
    LanguageConfig::new("Perl", &[".pl"], &[], &PERL_STYLE),
    LanguageConfig::new("Ruby", &[".rb"], &[], &RUBY_STYLE),
    LanguageConfig::new("C Header File", &[".h"], &[], &C_STYLE),
    LanguageConfig::new("C++ Header File", &[".h++", ".hh", ".hpp"], &[], &C_STYLE),
    LanguageConfig::new("C#", &[".cs"], &[], &C_STYLE),
    LanguageConfig::new("TypeScript", &[".ts"], &[], &C_STYLE),
    LanguageConfig::new("React JavaScript", &[".jsx"], &[], &C_STYLE),
    LanguageConfig::new("React TypeScript", &[".tsx"], &[], &C_STYLE),
    LanguageConfig::new("Rust", &[".rs"], &[], &C_STYLE),
    LanguageConfig::new("PHP", &[".php"], &[], &C_STYLE),
    LanguageConfig::new("YAML", &[".yaml", ".yml"], &[], &SHELL_STYLE),
    LanguageConfig::new("JSON", &[".json"], &[], &NO_COMMENT),
    LanguageConfig::new("Cython", &[".pxd", ".pxi", ".pyx"], &[], &PYTHON_STYLE),
    LanguageConfig::new("CSS", &[".css"], &[], &C_STYLE),
    LanguageConfig::new("HTML", &[".htm", ".html"], &[], &HTML_STYLE),
    LanguageConfig::new("XML", &[".xml"], &[], &HTML_STYLE),
    LanguageConfig::new("Dart", &[".dart"], &[], &C_STYLE),
    LanguageConfig::new("Kotlin", &[".kt"], &[], &C_STYLE),
    LanguageConfig::new("SQL", &[".sql"], &[], &SQL_STYLE),
    LanguageConfig::new("Vim Script", &[".vim"], &[".vimrc"], &VIM_STYLE),
    LanguageConfig::new("Godot Script", &[".gd"], &[], &GODOT_STYLE),
    LanguageConfig::new("Lua", &[".lua"], &[], &LUA_STYLE),
    LanguageConfig::new("Lisp", &[".lisp", ".lsp"], &[], &LISP_STYLE),
    LanguageConfig::new("Scala", &[".sc", ".scala"], &[], &C_STYLE),
    LanguageConfig::new("CMake", &[".cmake"], &[], &SHELL_STYLE),
    LanguageConfig::new("Nix", &[".nix"], &[], &SHELL_STYLE),
    LanguageConfig::new("Assembly", &[".asm"], &[], &ASM_STYLE),
    LanguageConfig::new("Objective-C", &[".m"], &[], &C_STYLE),
    LanguageConfig::new("Objective-C++", &[".mm"], &[], &C_STYLE),
    LanguageConfig::new("PowerShell", &[".ps1"], &[], &SHELL_STYLE),
    LanguageConfig::new("Meson", &[".meson"], &[], &MESON_STYLE),
    LanguageConfig::new("Makefile", &[], &["Makefile"], &SHELL_STYLE),
    LanguageConfig::new("R", &[".r"], &[], &SHELL_STYLE),
    LanguageConfig::new("Zig", &[".zig"], &[], &C_STYLE),
    LanguageConfig::new("Scheme", &[".scm"], &[], &LISP_STYLE),
    LanguageConfig::new("Groovy", &[".groovy"], &[], &C_STYLE),
    LanguageConfig::new("Smalltalk", &[".st"], &[], &SMALLTALK_STYLE),
    LanguageConfig::new("Haskell", &[".hs"], &[], &HASKELL_STYLE),
    LanguageConfig::new("Nim", &[".nim"], &[], &NIM_STYLE),
    LanguageConfig::new("Julia", &[".jl"], &[], &JULIA_STYLE),
    LanguageConfig::new("Coffee Script", &[".coffee"], &[], &COFFEE_SCRIPT_STYLE),
    LanguageConfig::new("BASIC", &[".bas"], &[], &BASIC_STYLE),
    LanguageConfig::new("MATLAB", &[".mlx"], &[], &MATLAB_STYLE),
    LanguageConfig::new("Action Script", &[".as"], &[], &C_STYLE),
    LanguageConfig::new("Ada", &[".ada", ".adb"], &[], &ADA_STYLE),
    LanguageConfig::new("AutoHotkey Script", &[".ahk"], &[], &AUTOHOTKEY_STYLE),
    LanguageConfig::new("Carbon", &[".carbon"], &[], &C_STYLE),
    LanguageConfig::new("Swift", &[".swift"], &[], &C_STYLE),
    LanguageConfig::new("Emacs Lisp", &[".el", ".elc", ".eln"], &[], &LISP_STYLE),
    LanguageConfig::new("Fantom", &[".fan"], &[], &C_STYLE),
    LanguageConfig::new("Erlang", &[".erl"], &[], &ERLANG_STYLE),
    LanguageConfig::new("Crytal", &[".cr"], &[], &SHELL_STYLE),
    LanguageConfig::new("Clojure", &[".clj"], &[], &CLOJURE_STYLE),
    LanguageConfig::new("COBOL", &[".cbl"], &[], &COBOL_STYLE),
    LanguageConfig::new("D", &[".d"], &[], &C_STYLE),
    LanguageConfig::new("Dylan", &[".dylan"], &[], &C_STYLE),
    LanguageConfig::new("Fortran", &[".f", ".f95"], &[], &FORTRAN_STYLE),
    LanguageConfig::new("OCaml", &[".ml"], &[], &OCAML_STYLE),
    LanguageConfig::new("Eiffel", &[".e"], &[], &EIFFEL_STYLE),
    LanguageConfig::new("Pascal", &[".pas"], &[], &PASCAL_STYLE),
    LanguageConfig::new("TCL", &[".tcl"], &[], &SHELL_STYLE),
    LanguageConfig::new("Elixir", &[".ex", ".exs"], &[], &ELIXIR_STYLE),
    LanguageConfig::new("Markdown", &[".md"], &[], &NO_COMMENT),
    LanguageConfig::new("M4", &[".m4"], &[], &SHELL_STYLE),
    LanguageConfig::new("Kotlin Build Script", &[".kts"], &[], &C_STYLE),
    LanguageConfig::new("V Lang", &[".v", ".vsh"], &[], &C_STYLE),
    LanguageConfig::new("Visual Basic", &[".vb"], &[], &BASIC_STYLE),
    LanguageConfig::new("Batch File", &[".bat", ".cmd"], &[], &BATCHFILE_STYLE),
    LanguageConfig::new("SCSS", &[".scss"], &[], &C_STYLE),
    LanguageConfig::new("QML", &[".qml"], &[], &C_STYLE),
    LanguageConfig::new("Verilog", &[".verilog", ".vlg"], &[], &C_STYLE),
    LanguageConfig::new("F#", &[".fs"], &[], &FSHARP_STYLE),
    LanguageConfig::new("Jupyter Notebook", &[".ipynb"], &[], &NO_COMMENT),
    LanguageConfig::new("VHDL", &[".vhd"], &[], &VHDL_STYLE),
    LanguageConfig::new("Fish Script", &[".fish"], &[], &SHELL_STYLE),
    LanguageConfig::new("Tex", &[".tex"], &[], &TEX_STYLE),
    LanguageConfig::new("KornShell", &[".ksh"], &[], &SHELL_STYLE),
    LanguageConfig::new("Zsh", &[".zsh"], &[], &SHELL_STYLE),
    LanguageConfig::new("Dockerfile", &[], &["Dockerfile"], &SHELL_STYLE),
    LanguageConfig::new("Apple Script", &[".applescript"], &[], &C_STYLE),
    LanguageConfig::new("Unreal Script", &[".uc"], &[], &C_STYLE),
    LanguageConfig::new("ASP.NET", &[".asp"], &[], &HTML_STYLE),
    LanguageConfig::new("ASPX", &[".aspx"], &[], &HTML_STYLE),
    LanguageConfig::new("GLSL", &[".glsl"], &[], &C_STYLE),
    LanguageConfig::new("Cg", &[".cg"], &[], &C_STYLE),
    LanguageConfig::new("HLSL", &[".hlsl"], &[], &C_STYLE),
    LanguageConfig::new("OpenCL", &[".cl"], &[], &C_STYLE),
    LanguageConfig::new("CUDA", &[".cu"], &[], &C_STYLE),
    LanguageConfig::new("GraphQL", &[".gql", ".graphql"], &[], &SHELL_STYLE),
    LanguageConfig::new("Apache Config", &[], &[".htaccess"], &SHELL_STYLE),
    LanguageConfig::new("TOML", &[".toml"], &[], &SHELL_STYLE),
    LanguageConfig::new("Jinja2 Template", &[".j2"], &[], &NO_COMMENT),
    LanguageConfig::new("GameMarker Studio", &[".gml"], &[], &C_STYLE),
    LanguageConfig::new("Brainfuck", &[".bf"], &[], &NO_COMMENT),
    LanguageConfig::new("Chef", &[".chef"], &[], &NO_COMMENT),
    LanguageConfig::new("APL", &[".apl"], &[], &NO_COMMENT),
];

#[rustfmt::skip]
#[must_use]
pub const fn builtin_languages() -> &'static [LanguageConfig] {
    BUILTIN_LANGUAGES
}

#[rustfmt::skip]
static EXACT_NAME_INDEX: Map<&'static str, usize> = phf_map! {
    ".htaccess" => 96usize,
    ".vimrc" => 26usize,
    "Dockerfile" => 85usize,
    "Makefile" => 38usize,
};

#[rustfmt::skip]
static EXTENSION_INDEX: Map<&'static str, usize> = phf_map! {
    "ada" => 51usize,
    "adb" => 51usize,
    "ahk" => 52usize,
    "apl" => 102usize,
    "applescript" => 86usize,
    "as" => 50usize,
    "asm" => 33usize,
    "asp" => 88usize,
    "aspx" => 89usize,
    "bas" => 48usize,
    "bat" => 74usize,
    "bf" => 100usize,
    "c" => 5usize,
    "c++" => 4usize,
    "carbon" => 53usize,
    "cbl" => 60usize,
    "cc" => 4usize,
    "cg" => 91usize,
    "chef" => 101usize,
    "cl" => 93usize,
    "clj" => 59usize,
    "cmake" => 31usize,
    "cmd" => 74usize,
    "coffee" => 47usize,
    "cpp" => 4usize,
    "cr" => 58usize,
    "cs" => 11usize,
    "css" => 20usize,
    "cu" => 94usize,
    "cxx" => 4usize,
    "d" => 61usize,
    "dart" => 23usize,
    "dylan" => 62usize,
    "e" => 65usize,
    "el" => 55usize,
    "elc" => 55usize,
    "eln" => 55usize,
    "erl" => 57usize,
    "ex" => 68usize,
    "exs" => 68usize,
    "f" => 63usize,
    "f95" => 63usize,
    "fan" => 56usize,
    "fish" => 81usize,
    "fs" => 78usize,
    "gd" => 27usize,
    "glsl" => 90usize,
    "gml" => 99usize,
    "go" => 6usize,
    "gql" => 95usize,
    "graphql" => 95usize,
    "groovy" => 42usize,
    "h" => 9usize,
    "h++" => 10usize,
    "hh" => 10usize,
    "hlsl" => 92usize,
    "hpp" => 10usize,
    "hs" => 44usize,
    "htm" => 21usize,
    "html" => 21usize,
    "ipynb" => 79usize,
    "j2" => 98usize,
    "java" => 1usize,
    "jl" => 46usize,
    "js" => 2usize,
    "json" => 18usize,
    "jsx" => 13usize,
    "ksh" => 83usize,
    "kt" => 24usize,
    "kts" => 71usize,
    "lisp" => 29usize,
    "lsp" => 29usize,
    "lua" => 28usize,
    "m" => 34usize,
    "m4" => 70usize,
    "md" => 69usize,
    "meson" => 37usize,
    "mjs" => 2usize,
    "ml" => 64usize,
    "mlx" => 49usize,
    "mm" => 35usize,
    "nim" => 45usize,
    "nix" => 32usize,
    "pas" => 66usize,
    "php" => 16usize,
    "pl" => 7usize,
    "ps1" => 36usize,
    "pxd" => 19usize,
    "pxi" => 19usize,
    "py" => 0usize,
    "pyx" => 19usize,
    "qml" => 76usize,
    "r" => 39usize,
    "rb" => 8usize,
    "rs" => 15usize,
    "sc" => 30usize,
    "scala" => 30usize,
    "scm" => 41usize,
    "scss" => 75usize,
    "sh" => 3usize,
    "sql" => 25usize,
    "st" => 43usize,
    "swift" => 54usize,
    "tcl" => 67usize,
    "tex" => 82usize,
    "toml" => 97usize,
    "ts" => 12usize,
    "tsx" => 14usize,
    "uc" => 87usize,
    "v" => 72usize,
    "vb" => 73usize,
    "verilog" => 77usize,
    "vhd" => 80usize,
    "vim" => 26usize,
    "vlg" => 77usize,
    "vsh" => 72usize,
    "xml" => 22usize,
    "yaml" => 17usize,
    "yml" => 17usize,
    "zig" => 40usize,
    "zsh" => 84usize,
};

#[rustfmt::skip]
#[must_use]
pub fn language_for_path(path: &Path) -> Option<LanguageMatch> {
    let file_name = path.file_name()?.to_str()?;

    if let Some(&index) = EXACT_NAME_INDEX.get(file_name) {
        return Some(language_match(index));
    }

    let extension = path.extension()?.to_str()?;
    EXTENSION_INDEX.get(extension).map(|&index| language_match(index))
}

#[rustfmt::skip]
#[must_use]
fn language_match(index: usize) -> LanguageMatch {
    (index, &BUILTIN_LANGUAGES[index])
}
