# Sephera Project: Programming Language Config.
# This project is licensed under the GNU General Public License v3.0.

# Comment Styles for programming languages.
comment_styles:
  c_style:
    single_line: "//"
    multi_line_start: "/*"
    multi_line_end: "*/"

  python_style:
    single_line: "#"
    multi_line_start: '"""'
    multi_line_end: '"""'
  
  shell_style:
    single_line: "#"

  perl_style:
    single_line: "#"
    multi_line_start: "="
    multi_line_end: "=cut"

  ruby_style:
    single_line: "#"
    multi_line_start: "=begin"
    multi_line_end: "=end"
  
  no_comment:
    single_line: null
    multi_line_start: null
    multi_line_end: null

  html_style:
    single_line: null
    multi_line_start: "<!--"
    multi_line_end: "-->"

  sql_style:
    single_line: "--"
    multi_line_start: "/*"
    multi_line_end: "*/"

  vim_style:
    single_line: "\""
    multi_line_start: null
    multi_line_end: null 

  godot_style:
    single_line: "#"
    multi_line_start: null
    multi_line_end: null

  lua_style:
    single_line: "--"
    multi_line_start: "--[["
    multi_line_end: "]]"

  lisp_style:
    single_line: ";"
    multi_line_start: "#|"
    multi_line_end: "|#"
  
  asm_style:
    single_line: ";"
    multi_line_start: null
    multi_line_end: null

  meson_style:
    single_line: "#"
    multi_line_start: "/*"
    multi_line_end: "*/"

  smalltalk_style:
    single_line: "\""
    multi_line_start: null
    multi_line_end: null

  haskell_style:
    single_line: "--"
    multi_line_start: "{-"
    multi_line_end: "-}"
  
  nim_style:
    single_line: "#"
    multi_line_start: "#["
    multi_line_end: "]#"

  julia_style:
    single_line: "#"
    multi_line_start: "#="
    multi_line_end: "=#"

# Languages extension, name, and comment style configuration.
languages:
  - name: Python
    extension:
      - .py
    comment_styles: python_style

  - name: Java
    extension:
      - .java
    comment_styles: c_style
  
  - name: JavaScript
    extension:
      - .js
      - .jsx
      - .mjs
    comment_styles: c_style

  - name: Shell Script
    extension:
      - .sh
    comment_styles: shell_style

  - name: C++
    extension:
      - .cc
      - .cpp
      - .cxx
      - .c++
    comment_styles: c_style

  - name: Golang
    extension:
      - .go
    comment_styles: c_style

  - name: Perl
    extension:
      - .pl
    comment_styles: perl_style

  - name: Ruby
    extension:
    - .rb
    comment_styles: ruby_style

  - name: C Header File
    extension:
    - .h
    comment_styles: c_style
  
  - name: C++ Header File
    extension:
    - .hpp
    - .hh
    - .h++
    comment_styles: c_style

  - name: C#
    extension:
    - .cs
    comment_styles: c_style

  - name: TypeScript
    extension:
    - .ts
    - .tsx
    comment_styles: c_style
  
  - name: Rust
    extension:
    - .rs
    comment_styles: c_style

  - name: PHP
    extension: 
    - .php
    comment_styles: c_style

  - name: YAML
    extension:
    - .yml
    - .yaml
    comment_styles: shell_style

  - name: JSON
    extension:
    - .json 
    comment_styles: no_comment

  - name: Cython
    extension:
    - .pyx
    - .pxd
    - .pxi
    comment_styles: python_style

  - name: CSS
    extension:
    - .css
    comment_styles: c_style
  
  - name: HTML
    extension:
    - .html
    - .htm 
    comment_styles: html_style

  - name: XML
    extension:
    - .xml
    comment_styles: html_style

  - name: Dart
    extension:
    - .dart
    comment_styles: c_style
  
  - name: Kotlin
    extension:
    - .kt
    comment_styles: c_style

  - name: SQL
    extension:
    - .sql
    comment_styles: sql_style

  - name: Vim Script
    extension:
    - .vim
    - .vimrc
    comment_styles: vim_style

  - name: Godot Script
    extension:
    - .gd
    comment_styles: godot_style

  - name: Lua
    extension:
    - .lua
    comment_styles: lua_style
  
  - name: Lisp
    extension:
    - .lisp
    - .lsp
    comment_styles: lisp_style

  - name: Scala
    extension:
    - .scala
    - .sc
    comment_styles: c_style

  - name: CMake
    extension:
    - .cmake
    comment_styles: shell_style
  
  - name: Nix
    extension:
    - .nix
    comment_styles: shell_style
  
  - name: Assembly
    extension:
    - .asm
    comment_styles: asm_style
  
  - name: Objective-C
    extension:
    - .m
    comment_styles: c_style
  
  - name: Objective-C++
    extension:
    - .mm
    comment_styles: c_style

  - name: PowerShell
    extension:
    - .ps1
    comment_styles: shell_style
  
  - name:  Meson
    extension:
    - .meson
    comment_styles: meson_style
  
  - name: Makefile
    extension:
    - Makefile
    comment_styles: shell_style
  
  - name: R
    extension:
    - .r
    comment_styles: shell_style

  - name: Zig
    extension:
    - .zig
    comment_styles: c_style
  
  - name: Scheme
    extension:
    - .scm
    comment_styles: lisp_style

  - name: Groovy
    extension:
    - .groovy
    comment_styles: c_style

  - name: Smalltalk
    extension:
    - .st
    comment_styles: smalltalk_style
  
  - name: Haskell
    extension:
    - .hs
    comment_styles: haskell_style
  
  - name: Nim
    extension:
    - .nim
    comment_styles: nim_style
  
  - name: Julia
    extension:
    - .jl
    comment_styles:

  