[usage]
main = """ 
Usage: sephera [options...]

    loc                        Quickly calculate total lines of code in your project.
    stats                      Show your project stats, size, number of files and folders. Optional chart output.
    tree                       Show your project structure tree. Optional chart output.
    update                     Update Sephera to the latest version or install it to a different directory path.
    language-support           Show the count of languages currently supported by Sephera.

[+] Markdown documentation: https://github.com/Reim-developer/Sephera/tree/master/docs
[+] Website documentation: https://reim-developer.github.io/Sephera
[+] Use `sephera --help [command]` for more information.

"""

loc_command = """
Usage: sephera loc [arguments...]

Arguments:
    --path <path>              Path to your project. (Default: current directory)
    --ignore <pattern>         Regex pattern to ignore files or folders. Can be used multiple times.
"""

stats_command = """
Usage: sephera stats [arguments...]

Arguments:
    --path <path>              Path to scan. (Default: current directory)
    --ignore <pattern>         Regex, glob, or name pattern to ignore files or folders (e.g. --ignore '__pycache__')
    --chart [<save_path>]      Create chart for your stat overview. Default chart name is 'SepheraChart'.
"""

tree_command = """
Usage: sephera tree [arguments...]

Arguments:
    --path <path>              Path to scan. (Default: current directory)
    --ignore <pattern>         Regex, or name pattern to ignore files or folders (e.g. --ignore '__pycache__')
    --chart [<save_path>]      Create chart for your directory tree. Default chart name is 'SepheraChart'.
"""

language_support_command = """
Usage: sephera language-support [arguments...]

Arguments:
    --list                     Show the list of language names currently supported by Sephera.
"""

update_command = """
Usage: sephera update

[+] Update Sephera to the latest version or install it to a different directory path.
"""