//! Benchmarks for the `loc` hot paths.
//!
//! Two layers, because they answer different questions.
//!
//! [`scan_content`] is the classifier: given bytes already in hand, how fast can
//! it decide code from comment from blank? This is where a change to the
//! delimiter search shows up, with the filesystem nowhere in the picture.
//!
//! [`CodeLoc::analyze`] is the command: traversal, ignore rules, metadata, and
//! `mmap` included. It is slower per byte and it is what a user waits for, so a
//! microbenchmark that only improves the first number can still leave the command
//! exactly as slow.
//!
//! The inputs are generated rather than checked in. A 2 MiB fixture in the tree
//! is a fixture that rots, and a fixture that happens to be well-formatted
//! measures comment detection on input no real repository contains. Each shape
//! here corresponds to something the scanner actually meets: mostly-code Rust,
//! a language with no block comments at all, a header dominated by block
//! comments, and CRLF, which is a separate code path through the line splitter
//! rather than a variation on the same one.

use std::hint::black_box;

use criterion::{Criterion, Throughput, criterion_group, criterion_main};

use sephera_scan::{CodeLoc, IgnoreMatcher, scan_content};
use sephera_core::config::CommentStyle;

/// A tiny LCG, so the generated bytes are identical on every machine and run.
///
/// `char::from_u32` arithmetic was the obvious alternative and it is wrong here:
/// it would emit whatever Unicode a given number happens to decode to, including
/// astral-plane characters that are four bytes wide and would make the line
/// length distribution depend on the encoding's alignment.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        // Constants from Numerical Recipes; the point is that it is not zero.
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        self.0 >> 33
    }

    fn below(&mut self, bound: u64) -> u64 {
        self.next() % bound
    }
}

const CODE_SNIPPETS: &[&str] = &[
    "let value = compute(input, offset)?;",
    "pub fn resolve(&self, path: &Path) -> Result<Resolved> {",
    "    metrics.code_lines += 1;",
    "if let Some(node) = tree.root_node().child(i) {",
    "    return Ok(report);",
    "}",
    "match self.style { Style::Line => 1, Style::Block => 2 }",
    "    let total = items.iter().map(Item::cost).sum::<u64>();",
];

const LINE_COMMENTS: &[&str] = &[
    "// A line comment.",
    "//  Indented line comment.",
    "    // trailing comment after a statement",
    "//",
];

/// Build a source file of roughly `target_bytes`.
///
/// The mix is fixed rather than random so that a regression compares like with
/// like: a scanner that got slower because the generator emitted more block
/// comments would read as a scanner regression.
fn synth(
    target_bytes: usize,
    block_comment_every: Option<usize>,
    newline: &str,
) -> String {
    let mut rng = Rng(0x5EED_1234_ABCD_0001);
    let mut out = String::with_capacity(target_bytes + 128);
    let mut line_number = 0_usize;
    let mut in_block = false;

    while out.len() < target_bytes {
        line_number += 1;
        if in_block {
            if line_number % 4 == 0 {
                out.push_str(" */");
                out.push_str(newline);
                in_block = false;
            } else {
                out.push_str(
                    " an unremarkable continuation line of the block comment.",
                );
                out.push_str(newline);
            }
            continue;
        }

        if let Some(every) = block_comment_every
            && line_number % every == 0
        {
            out.push_str("/*");
            out.push_str(newline);
            in_block = true;
            continue;
        }

        let pick = rng.below(100);
        if pick < 12 {
            out.push_str(
                LINE_COMMENTS[(rng.below(LINE_COMMENTS.len() as u64)) as usize],
            );
        } else {
            out.push_str(
                CODE_SNIPPETS[(rng.below(CODE_SNIPPETS.len() as u64)) as usize],
            );
        }
        out.push_str(newline);
    }

    out
}

const RUST_STYLE: CommentStyle =
    CommentStyle::new(Some("//"), Some("/*"), Some("*/"));
/// Python has no block comment, so the multi-line branch is never taken. This is
/// the shape that a scanner optimised only for block comments will silently lose.
const PYTHON_STYLE: CommentStyle = CommentStyle::new(Some("#"), None, None);
const COMMENTLESS_STYLE: CommentStyle = CommentStyle::new(None, None, None);

fn bench_scan(criterion: &mut Criterion) {
    let mut group = criterion.benchmark_group("loc/scan_content");

    let cases: [(&str, Vec<u8>, &CommentStyle); 6] = [
        (
            "rust_2MiB",
            synth(2 << 20, Some(37), "\n").into_bytes(),
            &RUST_STYLE,
        ),
        (
            "rust_block_heavy_2MiB",
            synth(2 << 20, Some(6), "\n").into_bytes(),
            &RUST_STYLE,
        ),
        (
            "python_2MiB",
            synth(2 << 20, None, "\n").into_bytes(),
            &PYTHON_STYLE,
        ),
        (
            "rust_crlf_2MiB",
            synth(2 << 20, Some(37), "\r\n").into_bytes(),
            &RUST_STYLE,
        ),
        (
            "commentless_2MiB",
            synth(2 << 20, Some(37), "\n").into_bytes(),
            &COMMENTLESS_STYLE,
        ),
        ("empty", Vec::new(), &RUST_STYLE),
    ];

    for (name, bytes, style) in cases {
        group.throughput(Throughput::Bytes(bytes.len() as u64));
        group.bench_function(name, |bencher| {
            bencher.iter(|| scan_content(black_box(&bytes), black_box(style)));
        });
    }

    group.finish();
}

/// A small tree on disk, so [`CodeLoc::analyze`] is measured with the traversal
/// and the syscalls it will always have.
fn write_tree(
    root: &std::path::Path,
    directories: usize,
    files_per_directory: usize,
) {
    let source = synth(48 << 10, Some(11), "\n");
    for directory in 0..directories {
        let path = root.join(format!("crate-{directory:03}"));
        std::fs::create_dir_all(&path).expect("benchmark tree is writable");
        for file in 0..files_per_directory {
            // Mixed extensions so the language table is exercised rather than
            // every file taking the same lookup.
            let extension = if file % 3 == 0 { "rs" } else { "py" };
            std::fs::write(
                path.join(format!("mod-{file:03}.{extension}")),
                &source,
            )
            .expect("benchmark tree is writable");
        }
    }
}

/// A tree of small files, which is what a repository is made of.
///
/// The generated corpora are 898 files in 16 directories; a real repository is
/// the other way round. These two shapes hold the file count against the
/// directory count in opposite directions so the walk and the file reads can be
/// told apart from `analyze`'s total: one directory per few files makes
/// `read_dir` and the per-directory rule lookup the cost, many files per
/// directory makes opening and reading them the cost.
fn write_small_files(
    root: &std::path::Path,
    directories: usize,
    files_per_directory: usize,
) {
    let source = synth(2 << 10, Some(19), "\n");
    for directory in 0..directories {
        let path = root.join(format!("module_{directory:04}"));
        std::fs::create_dir_all(&path).expect("benchmark tree is writable");
        for file in 0..files_per_directory {
            std::fs::write(path.join(format!("file_{file:03}.rs")), &source)
                .expect("benchmark tree is writable");
        }
    }
}

fn bench_analyze(criterion: &mut Criterion) {
    let mut group = criterion.benchmark_group("loc/analyze");

    let temporary =
        tempfile::tempdir().expect("a temporary directory is available");
    write_tree(temporary.path(), 12, 25);

    group.throughput(Throughput::Bytes(0));
    group.bench_function("tree_300_files", |bencher| {
        bencher.iter(|| {
            let analyzer =
                CodeLoc::new(temporary.path(), IgnoreMatcher::default());
            black_box(analyzer.analyze().expect("the benchmark tree scans"))
        });
    });

    let wide = tempfile::tempdir().expect("a temporary directory is available");
    write_small_files(wide.path(), 500, 8);

    let flat = tempfile::tempdir().expect("a temporary directory is available");
    write_small_files(flat.path(), 4, 1000);

    group.bench_function("4000_files_500_dirs", |bencher| {
        bencher.iter(|| {
            let analyzer = CodeLoc::new(wide.path(), IgnoreMatcher::default());
            black_box(analyzer.analyze().expect("the benchmark tree scans"))
        });
    });

    group.bench_function("4000_files_4_dirs", |bencher| {
        bencher.iter(|| {
            let analyzer = CodeLoc::new(flat.path(), IgnoreMatcher::default());
            black_box(analyzer.analyze().expect("the benchmark tree scans"))
        });
    });

    group.finish();
}

criterion_group!(benches, bench_scan, bench_analyze);
criterion_main!(benches);
