name: Sephera Workflows
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Clang for Linux
        if: matrix.os == 'ubuntu-latest'
        
        run: |
          sudo apt-get update && sudo apt-get install -y clang
        shell: bash

      - name: Install Clang for macOS
        if: matrix.os == 'macos-latest'

        run: |
          brew install llvm
          echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
        shell: bash

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          output-filename: 'Sephera_${{ runner.os }}'
          extra-args: |
            --show-progress
            --nofollow-import-to=tests,examples,test
            --noinclude-pytest=nofollow
            --lto=yes
            ${{ matrix.os != 'windows-latest' && '--clang' || '' }}
            --jobs=4
            --static-libpython=yes
            --output-dir=build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4

        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true