name: Sephera Worflows
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            binary_name: sephera
            artifact_path: dist/sephera

          - os: windows-latest
            binary_name: sephera.exe
            artifact_path: dist/sephera.exe

          - os: macos-latest
            binary_name: sephera
            artifact_path: dist/sephera

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile --name ${{ matrix.binary_name }} main.py
        env:
          PYTHONPATH: .

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binary
          path: ${{ matrix.artifact_path }}
