name: Sephera Workflows
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Check syntax
        run: |
          ruff check .

      - name: Build executable for CLI
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          enable-console: true
          output-file: sephera-cli${{ runner.os == 'Windows' && '.exe' || '' }}
          output-dir: build/cli
          lto: yes

      - name: Build executable for GUI
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: gui/main.py
          mode: onefile
          enable-console: false
          enable-plugins: pyqt5
          macos-app-mode: gui
          output-file: sephera-gui${{ runner.os == 'Windows' && '.exe' || '' }}
          output-dir: build/gui
          lto: yes

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sephera-${{ runner.os }}
          path: |
            build/cli/sephera-cli${{ runner.os == 'Windows' && '.exe' || '' }}
            build/gui/sephera-gui${{ runner.os == 'Windows' && '.exe' || '' }}
          if-no-files-found: error
