name: Sephera Workflows
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Check syntax
        run: |
          ruff check .

      - name: Build executable for CLI
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          output-dir: build/cli
          lto: yes
      
      - name: Build executable for GUI
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: gui/main.py     
          mode: onefile
          lto: yes
          output-dir: build/gui

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/cli/*
            build/gui/*
          include-hidden-files: true